version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: static.dockerfile
    ports:
      - "3000:8080"
    links:
      - prediction
  prediction:
    build:
      context: .
    links:
      - postgres
    ports:
      - "3001:3000"
    environment:
    - PGUSER=postgres
    - PGHOST=postgres
    - PGPASSWORD=admin
    - PGDATABASE=foo
    - PGPORT=5432
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=foo
    volumes:
    - ./fixtures/:/docker-entrypoint-initdb.d/:ro
    ports:
      - "5432:5432"
volumes:
  logvolume01: {}
