collection = "nightly-220729"

[custom.all.shared]
type = "local"
path = "./src/Shared"
ipkg = "config.ipkg"

[custom.all.idris2-node-postgres]
type = "github"
url  = "https://github.com/alexhumphreys/idris2-node-postgres"
commit = "56a2090"
ipkg = "idris2-node-postgres.ipkg"

[custom.all.rhone-js]
type = "github"
url  = "https://github.com/alexhumphreys/idris2-rhone-js"
commit = "4dd396d3c856c731faa88fcc07f0dd44a859482b"
ipkg = "rhone-js.ipkg"
