name: build-test

on:
  - push

jobs:
  push-static-site:
    name: docker-compose build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Cache Docker
          uses: satackey/action-docker-layer-caching@v0.0.11
          # Ignore the failure of a step and avoid terminating the job.
          continue-on-error: true
        - name: docker-compose run
          run: |
            docker compose build
            docker compose up -d
        - name: make requests
          run: |
            make curl
